mp/drawing/urls.py
# from django.conf.urls import url, include
from django.urls import re_path, include
from drawing.views import *

urlpatterns = [
    # '',
    #drawings
    re_path(r'get_drawings$', get_drawings),
    re_path(r'delete_design/(?P<uid>[\w_]+)/$', delete_drawing), #user deletes drawing (or cancels empty geometry result)
    re_path(r'get_attributes/(?P<uid>[\w_]+)/$', get_attributes), #get attributes for a given scenario
    re_path(r'get_geometry_orig/(?P<uid>[\w_]+)/$', get_geometry_orig), #get geometry_orig wkt
    re_path(r'clip_to_grid$', get_clipped_shape),
    re_path(r'get_csv/(?P<uid>[\w_]+)/$', get_csv),
    #feature reports
    # url(r'wind_report/(\d+)', wind_analysis, name='wind_analysis'), #user requested wind energy site analysis
    re_path(r'aoi_report/(\d+)', aoi_analysis, name='aoi_analysis'), #user requested area of interest analysis
    re_path(r'get_report_print/$', get_report_print),
    re_path(r'get_report_print/(?P<uid>[\w_]+)/$', get_report_print),
    re_path(r'get_report_html/$', get_report_html),
    re_path(r'get_report_html/(?P<uid>[\w_]+)/$', get_report_html),
]

mp/urls.py
from django.conf.urls import url, include as old_include
from django.urls import re_path, include
from django.contrib import admin
from django.views.generic import RedirectView

from django.conf import settings
from data_manager.api import LayerResource, ThemeResource, TocThemeResource
from tastypie.api import Api
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from data_manager.views import import_export_admin, import_report_hex, get_current_fixture, create_data_manager_snapshot, data_manager_make_current
from map_proxy.views import mapproxy_view

from django.views import static

import visualize
import explore
#from mapproxy.views import proxy_view
#import map_proxy
# print(dir(map_proxy))
admin.autodiscover()

v1_api = Api(api_name='v1')
v1_api.register(LayerResource())
v1_api.register(ThemeResource())
v1_api.register(TocThemeResource())


urlpatterns = [
    # '',
    re_path(r'^admin/port_data_manager/$', import_export_admin),
    re_path(r'^admin/import_report_hex/$', import_report_hex),
    re_path(r'^admin/get_current_data_manager_fixture/$', get_current_fixture),
    re_path(r'^admin/create_data_manager_snapshot/$', create_data_manager_snapshot),
    re_path(r'^admin/data_manager_make_current/(?P<import_id>.*)$', data_manager_make_current),
    url(r'^admin/', admin.site.urls),
    # url('', include('social.apps.django_app.urls', namespace='social')),
    re_path(r'^api/', include(v1_api.urls)),
    re_path(r'^mp_profile/', include('mp_profile.urls')),
    #(r'^sdc/', include('scenarios.urls')),
    re_path(r'^drawing/', include('drawing.urls')),
    re_path(r'^data_manager/', include('data_manager.urls')),
    re_path(r'^content/', include('content.urls')),
    #(r'^learn/', include('learn.urls')),
    re_path(r'^scenario/', include('scenarios.urls')),
    re_path(r'^explore/', include('explore.urls')),
    re_path(r'^visualize/', include('visualize.urls')),
    re_path(r'^planner/', include('visualize.urls')),
    re_path(r'^embed/', include('visualize.urls')),
    re_path(r'^mobile/', include('visualize.urls')),
    re_path(r'^feedback/', include('feedback.urls')),
    re_path(r'^proxy/', include('mp_proxy.urls')),
    re_path(r'^mapproxy/(?P<path>.*)',
       mapproxy_view),
    re_path(r'^([\w-]*)/planner/', visualize.views.show_planner),
    re_path(r'^([\w-]*)/visualize/', visualize.views.show_planner),
    re_path(r'^([\w-]*)/embed/',
        visualize.views.show_embedded_map),
    re_path(r'^([\w-]*)/catalog/', explore.views.data_catalog),
    re_path(r'^$', RedirectView.as_view(url='/visualize')),
    re_path(r"^media/admin/(?P<path>.*)$",
           static.serve,
           {"document_root": settings.ADMIN_MEDIA_PATH}),
    re_path(r'^accounts/', include('madrona.openid.urls')),
    re_path(r'', include('madrona.openid.urls')),
    re_path(r'', include('madrona.common.urls')),
    re_path(r'^tinymce/', include('tinymce.urls')),
]


if settings.DEBUG:
    # urlpatterns = [
    #     url("^media/admin/(?P<path>.*)$",
    #     "django.views.static.serve",
    #     {"document_root": settings.ADMIN_MEDIA_PATH})] + urlpatterns
    urlpatterns += staticfiles_urlpatterns()

mp/content/models.py
from django.db import models
from tinymce.models import HTMLField

class Content(models.Model):
    name = models.CharField(max_length=100)
    display_name = models.CharField(max_length=255)
    description = models.TextField()
    content = HTMLField()

mp/drawing/models.py
from django.db import models
from django.utils.html import escape
from madrona.features import register
from madrona.features.models import PolygonFeature
from madrona.common.utils import LargestPolyFromMulti
from general.utils import sq_meters_to_sq_miles, format_precision
from drawing.ofr_manipulators import clip_to_grid, intersecting_cells
from drawing.reports import get_summary_reports

@register
class AOI(PolygonFeature):
    description = models.TextField(null=True,blank=True)

    @property
    def formatted_area(self):
        return int((self.area_in_sq_miles * 10) +.5) / 10.

    @property
    def area_in_sq_miles(self):
        return sq_meters_to_sq_miles(self.geometry_final.area)

    def summary_reports(self, attributes=None):
        # Call get_summary_reports with intersecting Grid Cells
        grid_cells = intersecting_cells(self.geometry_orig)
        if attributes and 'list_style' in attributes.keys():
            return get_summary_reports(grid_cells, attributes['list_style'])
        else:
            return get_summary_reports(grid_cells)

    @property
    def serialize_attributes(self):
        attributes = []
        attributes.extend(self.summary_reports())
        if self.description:
            attributes.append({'title': 'Description', 'data': self.description})
        return {'event': 'click', 'attributes': attributes}

    @classmethod
    def fill_color(self):
        return '776BAEFD'

    @classmethod
    def outline_color(self):
        return '776BAEFD'

    def clip_to_grid(self):
        geom = self.geometry_orig
        clipped_shape = clip_to_grid(geom)
        if clipped_shape:
            return LargestPolyFromMulti(clipped_shape)
        else:
            return clipped_shape

    @property
    def geojson_4326(self):
        geom = self.geometry_final
        geom.transform(4326)
        return geom.geojson

    def save(self, *args, **kwargs):
        self.geometry_final = self.clip_to_grid()
        # if self.geometry_final:
        #     self.geometry_final = clean_geometry(self.geometry_final)
        super(AOI, self).save(*args, **kwargs) # Call the "real" save() method

    class Options:
        verbose_name = 'Area of Interest'
        icon_url = 'img/aoi.png'
        export_png = False
        manipulators = []
        # manipulators = ['drawing.manipulators.ClipToPlanningGrid']
        # optional_manipulators = ['clipping.manipulators.ClipToShoreManipulator']
        form = 'drawing.forms.AOIForm'
        form_template = 'aoi/form.html'
        show_template = 'aoi/show.html'

mp/drawing/forms.py
from django import forms
from madrona.features.forms import FeatureForm, SpatialFeatureForm
from drawing.models import AOI
# from drawing.models import AOI, WindEnergySite

class AOIForm(SpatialFeatureForm):
    description = forms.CharField(widget=forms.Textarea(attrs={'cols': 30, 'rows': 3}), required=False)

    class Meta(SpatialFeatureForm.Meta):
        model = AOI

# class WindEnergySiteForm(SpatialFeatureForm):
#     class Meta(SpatialFeatureForm.Meta):
#         model = WindEnergySite

mp/drawing/views.py
from django.http import HttpResponse, Http404
from django.shortcuts import get_object_or_404, render
from django.contrib.gis.geos import GEOSGeometry
from django.core.exceptions import ObjectDoesNotExist
from madrona.features.models import Feature
from madrona.features import get_feature_by_uid
from madrona.common.utils import LargestPolyFromMulti
from scenarios.models import GridCell
from drawing.models import *
from drawing.ofr_manipulators import clip_to_grid
from json import dumps


'''
'''
def get_drawings(request):
    json = []
    if request.user.is_authenticated:
        drawings = AOI.objects.filter(user=request.user).order_by('date_created')
    else:
        drawings = AOI.objects.filter(user=None)
    for drawing in drawings:
        sharing_groups = [group.name for group in drawing.sharing_groups.all()]
        json.append({
            'id': drawing.id,
            'uid': drawing.uid,
            'name': drawing.name,
            'description': drawing.description,
            'attributes': drawing.serialize_attributes,
            'sharing_groups': sharing_groups
        })

    shared_drawings = AOI.objects.shared_with_user(request.user)
    for drawing in shared_drawings:
        if drawing not in drawings:
            username = drawing.user.username
            actual_name = drawing.user.first_name + ' ' + drawing.user.last_name
            json.append({
                'id': drawing.id,
                'uid': drawing.uid,
                'name': drawing.name,
                'description': drawing.description,
                'attributes': drawing.serialize_attributes,
                'shared': True,
                'shared_by_username': username,
                'shared_by_name': actual_name
            })

    return HttpResponse(dumps(json))

'''
'''
def delete_drawing(request, uid):
    try:
        drawing_obj = get_feature_by_uid(uid)
    except ObjectDoesNotExist:
        raise Http404
    except AttributeError:
        raise Http404

    #check permissions
    viewable, response = drawing_obj.is_viewable(request.user)
    if not viewable:
        return response

    drawing_obj.delete()

    return HttpResponse("", status=200)

'''
'''
def get_clipped_shape(request):
    zero = .01

    if not (request.POST and request.POST['target_shape']):
        return HTTPResponse("No shape submitted", status=400)

    target_shape = request.POST['target_shape']
    geom = GEOSGeometry(target_shape, srid=3857)

    clipped_shape = clip_to_grid(geom)

    # return new_shape['geometry__union']
    if clipped_shape and clipped_shape.area >= zero: #there was overlap
        largest_poly = LargestPolyFromMulti(clipped_shape)
        wkt = largest_poly.wkt
        return HttpResponse(dumps({"clipped_wkt": wkt}), status=200)
    else:
        return HttpResponse("Submitted Shape is outside Grid Cell Boundaries (no overlap).", status=400)

    # return HttpResponse(dumps({"clipped_wkt": wkt}), status=200)

'''
'''
def aoi_analysis(request, aoi_id):
    from aoi_analysis import display_aoi_analysis
    aoi_obj = get_object_or_404(AOI, pk=aoi_id)
    #check permissions
    viewable, response = aoi_obj.is_viewable(request.user)
    if not viewable:
        return response
    return display_aoi_analysis(request, aoi_obj)
    # Create your views here.

'''
'''
def get_attributes(request, uid):
    try:
        scenario_obj = get_feature_by_uid(uid)
    except Scenario.DoesNotExist:
        raise Http404

    #check permissions
    viewable, response = scenario_obj.is_viewable(request.user)
    if not viewable:
        return response

    return HttpResponse(dumps(scenario_obj.serialize_attributes))

def get_report_data(request, uid=None):
        try:
            scenario_obj = get_feature_by_uid(uid)
            #check permissions
            viewable, response = scenario_obj.is_viewable(request.user)
            if not viewable:
                return response

            context = scenario_obj.serialize_attributes
            context['title'] = scenario_obj.name
            context['map'] = scenario_obj.geojson_4326
        except (AttributeError, NameError) as e:
            attributes = []
            context = {'event': 'click', 'attributes': []}
            if request.method == 'POST':
                if 'parameter' in request.POST.dict().keys():
                    null = None # eval on null was crashing
                    try:
                        data = eval(request.POST.get('parameter'))
                    except NameError as e2:
                        # backup plan in case eval crashes on more stuff
                        import json
                        data = json.loads(request.POST.get('parameter'))
                    for item in data:
                        if item['display'] == 'map':
                            context['map'] = item['data']
                        else:
                            attributes.append({
                                'title': item['display'],
                                'data': item['data'],
                            })
                else:
                    data = request.POST.dict()
                    for key in data.keys():
                        attributes.append({
                            'title': key,
                            'data': data[key]
                        })
                context['attributes'] = attributes

        except Exception as e:
            raise Http404


        from datetime import datetime
        now = datetime.now()
        context['timestamp'] = now.strftime("%b %d, %Y")
        return context

def get_report_html(request, uid=None, template='aoi/reports/report.html'):
    context = get_report_data(request, uid)

    return render(request, template, context)

def get_report_print(request, uid=None, template='aoi/reports/report_print.html'):
    context = get_report_data(request, uid)
    if 'title' not in context.keys():
        context['title'] = 'Strategy Report'
    if 'description' not in context.keys():
        context['description'] = None

    for attr in context['attributes']:
        if attr['title'] == 'layer':
            context['title'] = attr['data']
        if attr['title'] == 'Description':
            context['description'] = attr['data']

    return render(request, template, context)

'''
'''
def get_geometry_orig(request, uid):
    try:
        scenario_obj = get_feature_by_uid(uid)
        wkt = scenario_obj.geometry_orig.wkt
    except Scenario.DoesNotExist:
        raise Http404

    #check permissions
    viewable, response = scenario_obj.is_viewable(request.user)
    if not viewable:
        return response

    return HttpResponse(dumps({"geometry_orig": wkt}), status=200)

'''
'''
# def wind_analysis(request, wind_id):
#     from wind_analysis import display_wind_analysis
#     wind_obj = get_object_or_404(WindEnergySite, pk=wind_id)
#     #check permissions
#     viewable, response = wind_obj.is_viewable(request.user)
#     if not viewable:
#         return response
#     return display_wind_analysis(request, wind_obj)
#     # Create your views here.

# Courtesy of Eloff: https://stackoverflow.com/a/925630
from html.parser import HTMLParser

class MLStripper(HTMLParser):
    def __init__(self):
        self.reset()
        self.strict = False
        self.convert_charrefs= True
        self.fed = []
    def handle_data(self, d):
        self.fed.append(d)
    def get_data(self):
        return ''.join(self.fed)

def strip_tags(html):
    s = MLStripper()
    s.feed(html)
    return s.get_data()


'''
'''
def get_csv(request, uid, download=True):
    import csv
    if 'drawing_aoi_' in uid:
        aoi_id = str(int(''.join([x for x in filter(str.isdigit, str(uid))])))
    else:
        aoi_id = int(uid)
    # aoi_id = int(request.POST['id'])
    try:
        drawing = AOI.objects.get(id=aoi_id)
    except:
        return HttpResponse(
            dumps(
                {
                    'message': 'Could not find drawing with id = %d' % aoi_id
                }
            ),
            status=500
        )
    filename = '%s_%d_drawing.csv' % (drawing.name, drawing.id)
    summaryReports = drawing.summary_reports({'list_style':'list'})
    if download:
        response = HttpResponse(content_type='text/csv')
        response['Content-Disposition'] = 'attachment; filename=%s' % (filename)
        writer = csv.writer(response)
    else:
        import settings
        csv_file = open('%s%s' % (settings.PUBLIC_CSV_DIR,filename), 'w')
        writer = csv.writer(csv_file)
    headers = ['Name']
    report_data = {'Name':drawing.name}
    max_row_count = 2   #for disclaimer
    for attribute in summaryReports:
        headers.append(strip_tags(attribute['title']))
        if type(attribute['data']) is (list or tuple):
            attr_length = len(attribute['data'])
            if attr_length > max_row_count:
                max_row_count = attr_length
        report_data[strip_tags(attribute['title'])] = attribute['data']

    # Move Observed Species to end of list to be next to disclaimer
    observed = 'Observed Wildlife'
    if observed in headers:
        headers.insert(len(headers)-1, headers.pop(headers.index(observed)))
    headers.append('Disclaimer')
    report_data['Disclaimer'] = [
    "Data used to generate this report has been summarized.",
    "See http://dfw.state.or.us/maps/compass/reportingtool.asp"
    ]

    writer.writerow(headers)
    for index in range(max_row_count):
        row = []
        for header in headers:
            if type(report_data[header]) is (list or tuple):
                data = [strip_tags(x) for x in report_data[header]]

mp/drawing/templates/aoi/form.html
{% extends "common/panel.html" %}
{% block title %}{{title}}{% endblock %}

{% block panel %}

<script type="text/javascript" charset="utf-8">
    madrona.onShow(function(){
        madrona.setupForm($('#polygon-design-form'));
        var max_step = 2;

        var step = 1;

        function validate(step) {
            return_value = true;
            if (step == 1) {
                if ( app.viewModel.scenarios.drawingFormModel.isDrawing()) {
                    $('#double-click-instructions').effect("highlight", {}, 1000);
                    return_value = false;
                } else if ( ! app.viewModel.scenarios.drawingFormModel.hasShape() ) {
                    $('#click-to-begin-drawing').effect("highlight", {}, 1000);
                    return_value = false;
                }
            } else if (step == max_step) {

            }
            return return_value;
        };

        function wizard(action) {
            if (step == 1 && action == 'next') {
                if (app.viewModel.scenarios.drawingFormModel.isEditing()) {
                    // do nothing, button is / should be disabled
                    return;
                }
                if (validate(step)) {
                    step += 1;
                    app.viewModel.scenarios.drawingFormModel.completeEdit();
                    $('#id_geometry_orig')[0].value = 'SRID=3857;' + new OpenLayers.Format.WKT().write(app.viewModel.scenarios.drawingFormModel.polygonLayer.features[0]);
                }
            } else if (step > 1 && action == 'prev') {
                step -= 1;
            }
            $('div.step').each(function(index) {
                $(this).hide();
            });
            $('div#step' + step).show();

            if (step == 1) {
                $('#drawing_prev').hide();
                $('#drawing_submit').hide();
            } else {
                $('#drawing_prev').show();
            }

            if (step == max_step) {
                $('#drawing_next').hide();
                $('.submit_button').show();
            } else {
                $('#drawing_next').show();
                $('.submit_button').hide();
            }
        };

        $('#drawing_prev').click( function() { wizard('prev'); });
        $('#drawing_next').click( function() { wizard('next'); });
        step = 1;
        {% if form.errors %}
            step = 2; // form errors exist
        {% endif %}
        wizard();


        $('#id_name').keypress(function (e) {
            if (e.which === 13) {
                $('#drawing-form .submit_button').click();
                return false;
            } else {
                $('#invalid-name-message').hide();
            }
        });
        /*
        $('#drawing-form .submit_button').click( function() {
            var name = $('#id_name').val();
            if ($.trim(name) !== "") {
                return true;
            }
            $('#invalid-name-message').show();
            return false;
        });
        */
        $('#click-to-begin-drawing').effect("highlight", {}, 1000);
    });
</script>

{% if form.media %} {{ form.media }} {% endif %}
<h4>
    Drawing
</h4>

<form id="polygon-design-form" action="{{action}}" method="post">
    {% for hidden in form.hidden_fields %}
        <div style="display:none;">
            {{ hidden.errors }}
        </div>
        {{ hidden }}
    {% endfor %}
    <div id="error_bar"></div>

    <div id="step1" class="step">
        <p class="step-text"><i>Step 1 of 2 </i>
        <div data-bind="visible: ! isDrawing() && ! showEdit()">
            <p id="click-to-begin-drawing" class="well instructions">Click the <b>Draw Shape</b> button below to begin drawing your polygon.</p>
            <a id="draw-shape-button" class="btn" style="margin-top: 10px" data-bind="click: startSketch, css: { disabled: isDrawing() }">
                <span>Draw Shape</span>
            </a>
        </div>
        <div data-bind="visible: isDrawing()">
            <div id="drawing-instructions" class="well">
                <div>
                    <b>Click on the map</b> to add the points that make up your polygon.
                </div>
                <div id="double-click-instructions" style="padding-top: 10px">
                    <b>Double-click</b> to finish drawing.
                </div>
            </div>
        </div>
        <div data-bind="visible: showEdit()">
            <div id="drawing-step-1" data-bind="visible: ! isEditing()">
                <div id="step-1-instructions" class="well">
                    <p class="instructions">Click <b>Next</b> if you are satisfied with your drawing.</p>
                    <p class="instructions" style="margin-top: 10px;">Click <b>Edit Shape</b> to make changes to your drawing.</p>
                </div>
                <a class="btn" style="margin-top: 10px" data-bind="click: startEdit, css: { disabled: isEditing() }">
                    <span>Edit Shape</span>
                </a>
            </div>
            <div id="draw-editing" data-bind="visible: isEditing()">
                <div id="editing-instructions" class="well">
                    <p class="instructions">
                        <b>Click and drag</b> the handles or vertices of the drawing.
                    </p>
                    <p class="instructions">
                        When you are done, click <b>Done Editing</b> below.
                    </p>
                </div>
                <a class="btn" style="margin-top: 10px" data-bind="click: clipToGrid">
                    <span>Done Editing</span>
                </a>
            </div>
            <div id="clip-failed-alert" style="margin-top: 10px;">
                <p class="alert alert-danger" data-bind="visible: clipAttemptFailed()">
                    Make sure your drawing overlaps with the planning grid...
                </p>
            </div>
        </div>
        <!--
        <div style="bottom: 66px; left-margin: 1px">
            <label id="planning-grid-layer-toggle" data-bind="click: togglePlanningGridLayer">
                <input id="planning-grid-layer-checkbox" data-bind="checked: planningGridLayer.active()" type="checkbox" name="checkbox" value="value">
                Show Planning Grid</input>
            </label>
        </div>
      -->
        <div id="PanelGeometry"></div>
    </div>

    <div class="step" id="step2">
        <p class="step-text"><i>Step 2 of 2 </i></p>
        <p class="instructions" style="margin-top: 10px">Provide a <b>name</b> to identify your drawing.</p>
        <div class="step3-inputs">
            <div class="step3-param">
                {{ form.name.errors }}
                {{ form.name }}
                <div id="invalid-name-message" class="control-group error" style="display: none; margin-top: -10px; margin-left: -5px;">
                    <span class="help-inline">The <b>Name</b> field is required.</span>
                </div>
            </div>
            <p class="instructions">Optionally, you may add a <b>description</b></p>
            <div class="step3-param">
                {{ form.description.errors }}
                {{ form.description }}
            </div>
        </div>
    </div>
</form>


<div class="wizard_nav" style="width:100%">
    <div class="btn-group pull-right" style="margin-right: 19px">
        <a href="#" class="button btn" onclick="this.blur(); return false;" id="drawing_prev"><span>&lt; Previous</span></a>
        <a href="#" class="button btn button-next"  onclick="this.blur(); return false;" id="drawing_next" data-bind="css: { disabled: isEditing() || !showEdit() }"><span>Next &gt;</span></a>
        <a href="#" class="submit_button button btn" onclick="this.blur(); return false;" id="drawing_save"><span>Save</span></a>
    </div>
</div>

<div>
    <div class="btn-group pull-left" style="margin-left: 14px">
        <a href="#" id="drawing_cancel" class="cancel_button button red btn"><span>Cancel</span></a>

    </div>
</div>

<style type="text/css">

</style>

{% endblock %}

mp/drawing/templates/aoi/show.html
{% extends 'common/panel.html' %}
{% block title %}{{instance.name}}{% endblock title %}
{% block panel %}

<h1>
    <img src="/media/marco/img/aoi.png"/>
    <small><small>Area of Interest </small></small> 
    &nbsp;&nbsp;{{instance.name}} 
</h1>
<div class="tabs">
    <ul>
        <li><a href="#Inputs"><span>Inputs</span></a></li>
        <li><a href="#reports"><span>Reports</span></a></li>
    </ul>
    <div id="Inputs">
        <ul class="metadata">
          {% if instance.user.first_name and instance.user.last_name %} 
            <li class="creator">Created By {{instance.user.first_name}} {{instance.user.last_name}}</li>
          {% else %}
            <li class="creator">Created By {{instance.user.username}}</li>
          {% endif %}
            <li class="created">Created {{instance.date_created|date:"d M, Y P"}}</li>
            <li class="modified">Modified {{instance.date_modified|date:"d M, Y P"}}</li>
            <br class="clear" />
        </ul>
        
        <h2>Description</h2>
            {% if instance.description %}
            <p><span class="label">{{instance.description}}</span></p>
            {% else %}
            <p><i>None Provided</i></p>
            {% endif %}
    </div>
    
    <div id="reports" class="tabs">
        <ul>
            <li><a href="{% url 'aoi_analysis' instance.pk %}"><span>Sample Report</span></a></li>
        </div>
    </div>
    
</div>

{% endblock panel %}